### ISSUE TITLE
Lien mort (ontherailsagain)

### ISSUE THREAD

**Issue by ghost** [simonc/jeveuxapprendreruby.fr#10]
Le lien vers http://ontherailsagain.com/ semble mort sur le site.
Pas beaucoup d'activité sur [Twitter](https://twitter.com/ontherailsblog), donc difficile de savoir si c'est définitif.

**Comment by simonc** [comment]
@Aasimar effectivement, on a mis le site à jour il y a peu pour indiquer le statut des entrées (actif, en pause, obsolète et mort) du coup On The Rails Again est effectivement mort.

On fera le tri pour garder que le contenu actif à terme.

Merci pour le feedback en tout cas :)

**Comment by simonc** [comment]
Voila, normalement tout est à jour 😌
